// <auto-generated />
using APIExamplePRN232.Data.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIExamplePRN232.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APIExamplePRN232.Data.Entities.Student", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentID"));

                    b.Property<string>("StudentAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StudentID1")
                        .HasColumnType("int");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentID");

                    b.HasIndex("StudentID1");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentID = 1,
                            StudentAddress = "123 Main St",
                            StudentName = "John Doe"
                        },
                        new
                        {
                            StudentID = 2,
                            StudentAddress = "456 Oak Ave",
                            StudentName = "Jane Smith"
                        },
                        new
                        {
                            StudentID = 3,
                            StudentAddress = "789 Elm Dr",
                            StudentName = "Michael Brown"
                        },
                        new
                        {
                            StudentID = 4,
                            StudentAddress = "321 Birch Ln",
                            StudentName = "Emily Johnson"
                        },
                        new
                        {
                            StudentID = 5,
                            StudentAddress = "654 Pine Rd",
                            StudentName = "David Lee"
                        },
                        new
                        {
                            StudentID = 6,
                            StudentAddress = "987 Maple St",
                            StudentName = "Sarah Wilson"
                        },
                        new
                        {
                            StudentID = 7,
                            StudentAddress = "741 Cedar Blvd",
                            StudentName = "Robert Martinez"
                        },
                        new
                        {
                            StudentID = 8,
                            StudentAddress = "852 Ash St",
                            StudentName = "Laura White"
                        },
                        new
                        {
                            StudentID = 9,
                            StudentAddress = "159 Spruce Ave",
                            StudentName = "Kevin Harris"
                        },
                        new
                        {
                            StudentID = 10,
                            StudentAddress = "753 Redwood Blvd",
                            StudentName = "Sophia Clark"
                        },
                        new
                        {
                            StudentID = 11,
                            StudentAddress = "264 Chestnut Ct",
                            StudentName = "Daniel King"
                        },
                        new
                        {
                            StudentID = 12,
                            StudentAddress = "978 Acacia Rd",
                            StudentName = "Olivia Lewis"
                        },
                        new
                        {
                            StudentID = 13,
                            StudentAddress = "183 Magnolia Ln",
                            StudentName = "James Hall"
                        },
                        new
                        {
                            StudentID = 14,
                            StudentAddress = "365 Willow St",
                            StudentName = "Mia Allen"
                        },
                        new
                        {
                            StudentID = 15,
                            StudentAddress = "572 Poplar Rd",
                            StudentName = "William Young"
                        },
                        new
                        {
                            StudentID = 16,
                            StudentAddress = "492 Cypress Blvd",
                            StudentName = "Emma Turner"
                        },
                        new
                        {
                            StudentID = 17,
                            StudentAddress = "611 Cherry St",
                            StudentName = "Henry Scott"
                        },
                        new
                        {
                            StudentID = 18,
                            StudentAddress = "284 Fir Ave",
                            StudentName = "Alice Adams"
                        },
                        new
                        {
                            StudentID = 19,
                            StudentAddress = "705 Juniper Ct",
                            StudentName = "Benjamin Carter"
                        },
                        new
                        {
                            StudentID = 20,
                            StudentAddress = "840 Dogwood Blvd",
                            StudentName = "Ella Baker"
                        });
                });

            modelBuilder.Entity("APIExamplePRN232.Data.Entities.Student", b =>
                {
                    b.HasOne("APIExamplePRN232.Data.Entities.Student", null)
                        .WithMany("Students")
                        .HasForeignKey("StudentID1");
                });

            modelBuilder.Entity("APIExamplePRN232.Data.Entities.Student", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
