// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eStoreWebAPI.Models;

#nullable disable

namespace eStoreWebAPI.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250520200510_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("eStoreWebAPI.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Electronics"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Books"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Clothing"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Groceries"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Toys"
                        });
                });

            modelBuilder.Entity("eStoreWebAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UnitsInStock")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 2,
                            ProductName = "Sample Product 1",
                            UnitPrice = 11.99m,
                            UnitsInStock = 101
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 3,
                            ProductName = "Sample Product 2",
                            UnitPrice = 12.99m,
                            UnitsInStock = 102
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 4,
                            ProductName = "Sample Product 3",
                            UnitPrice = 13.99m,
                            UnitsInStock = 103
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 5,
                            ProductName = "Sample Product 4",
                            UnitPrice = 14.99m,
                            UnitsInStock = 104
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 1,
                            ProductName = "Sample Product 5",
                            UnitPrice = 15.99m,
                            UnitsInStock = 105
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 2,
                            ProductName = "Sample Product 6",
                            UnitPrice = 16.99m,
                            UnitsInStock = 106
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 3,
                            ProductName = "Sample Product 7",
                            UnitPrice = 17.99m,
                            UnitsInStock = 107
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 4,
                            ProductName = "Sample Product 8",
                            UnitPrice = 18.99m,
                            UnitsInStock = 108
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 5,
                            ProductName = "Sample Product 9",
                            UnitPrice = 19.99m,
                            UnitsInStock = 109
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryId = 1,
                            ProductName = "Sample Product 10",
                            UnitPrice = 20.99m,
                            UnitsInStock = 110
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryId = 2,
                            ProductName = "Sample Product 11",
                            UnitPrice = 21.99m,
                            UnitsInStock = 111
                        },
                        new
                        {
                            ProductId = 12,
                            CategoryId = 3,
                            ProductName = "Sample Product 12",
                            UnitPrice = 22.99m,
                            UnitsInStock = 112
                        },
                        new
                        {
                            ProductId = 13,
                            CategoryId = 4,
                            ProductName = "Sample Product 13",
                            UnitPrice = 23.99m,
                            UnitsInStock = 113
                        },
                        new
                        {
                            ProductId = 14,
                            CategoryId = 5,
                            ProductName = "Sample Product 14",
                            UnitPrice = 24.99m,
                            UnitsInStock = 114
                        },
                        new
                        {
                            ProductId = 15,
                            CategoryId = 1,
                            ProductName = "Sample Product 15",
                            UnitPrice = 25.99m,
                            UnitsInStock = 115
                        },
                        new
                        {
                            ProductId = 16,
                            CategoryId = 2,
                            ProductName = "Sample Product 16",
                            UnitPrice = 26.99m,
                            UnitsInStock = 116
                        },
                        new
                        {
                            ProductId = 17,
                            CategoryId = 3,
                            ProductName = "Sample Product 17",
                            UnitPrice = 27.99m,
                            UnitsInStock = 117
                        },
                        new
                        {
                            ProductId = 18,
                            CategoryId = 4,
                            ProductName = "Sample Product 18",
                            UnitPrice = 28.99m,
                            UnitsInStock = 118
                        },
                        new
                        {
                            ProductId = 19,
                            CategoryId = 5,
                            ProductName = "Sample Product 19",
                            UnitPrice = 29.99m,
                            UnitsInStock = 119
                        },
                        new
                        {
                            ProductId = 20,
                            CategoryId = 1,
                            ProductName = "Sample Product 20",
                            UnitPrice = 30.99m,
                            UnitsInStock = 120
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
