// <auto-generated />
using System;
using DataLayer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataLayer.Migrations
{
    [DbContext(typeof(SP25PEDBContext))]
    partial class SP25PEDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataLayer.Entities.Categories", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Kỹ năng mềm"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Phát triển bản thân"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Kỹ năng chuyên môn"
                        });
                });

            modelBuilder.Entity("DataLayer.Entities.Courses", b =>
                {
                    b.Property<int>("CoursesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CoursesId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CoursesId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CoursesId = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 6, 11, 3, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cải thiện kỹ năng lắng nghe và trình bày.",
                            Price = 500000m,
                            Title = "Giao tiếp hiệu quả",
                            UserId = 1
                        },
                        new
                        {
                            CoursesId = 2,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 6, 11, 3, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Học cách sắp xếp công việc và cuộc sống.",
                            Price = 650000m,
                            Title = "Quản lý thời gian thông minh",
                            UserId = 1
                        },
                        new
                        {
                            CoursesId = 3,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 6, 11, 3, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Phối hợp hiệu quả để đạt mục tiêu chung.",
                            Price = 550000m,
                            Title = "Làm việc nhóm chuyên nghiệp",
                            UserId = 1
                        },
                        new
                        {
                            CoursesId = 4,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 6, 11, 3, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Phân tích thông tin và ra quyết định logic.",
                            Price = 700000m,
                            Title = "Tư duy phản biện",
                            UserId = 1
                        },
                        new
                        {
                            CoursesId = 5,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 6, 11, 3, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Các khái niệm cơ bản về C# và .NET.",
                            Price = 990000m,
                            Title = "Nhập môn Lập trình C#",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("DataLayer.Entities.Enrollments", b =>
                {
                    b.Property<int>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnrollmentId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("EnrollmentId");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId", "CourseId")
                        .IsUnique();

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("DataLayer.Entities.Users", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "teacher@example.com",
                            Password = "123123"
                        },
                        new
                        {
                            UserId = 2,
                            Email = "student@example.com",
                            Password = "123123"
                        });
                });

            modelBuilder.Entity("DataLayer.Entities.Courses", b =>
                {
                    b.HasOne("DataLayer.Entities.Categories", "Category")
                        .WithMany("Courses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataLayer.Entities.Users", "User")
                        .WithMany("Courses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataLayer.Entities.Enrollments", b =>
                {
                    b.HasOne("DataLayer.Entities.Courses", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataLayer.Entities.Users", "User")
                        .WithMany("Enrollments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataLayer.Entities.Categories", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("DataLayer.Entities.Courses", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("DataLayer.Entities.Users", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
